### ISSUE TITLE
App crash and i got this Error :   java.lang.NoSuchMethodError

### ISSUE THREAD

**Issue by ameerhamza6733** [nisrulz/lantern#1]
`  java.lang.NoSuchMethodError: No virtual method setTorchMode(Ljava/lang/String;Z)V in class Landroid/hardware/camera2/CameraManager; or its super classes (declaration of 'android.hardware.camera2.CameraManager' appears in /system/framework/framework.jar)`

Here how i try to use this lib

 ```
protected void onCreate(@Nullable Bundle savedInstanceState) {
        super.onCreate(savedInstanceState);
        Log.d("FlashLightActivty", "oncreate");
        Intent intent = getIntent();
        boolean flashLight = intent.getBooleanExtra(EXTRA_ON_OF, false);

        try {
            Lantern.getInstance().init(this);

        } catch (SecurityException e) {
           Toast.makeText(this,e.getMessage(),Toast.LENGTH_LONG).show();
        }
        if(flashLight)
            Lantern.getInstance().turnOnFlashlight(this);
        else
            Lantern.getInstance().turnOffFlashlight(this);
      //  Toast.makeText(this,"FlashLightActivtyReceiver",Toast.LENGTH_LONG).show();
    }
```

i try to test this on Samsung j2 with 5.1.1

**Comment by 0ximDigital** [comment]
This issue is happening on the HTC One M9 as well.
Android version 5.1

**Comment by bendavisnc** [comment]
I noticed that setTorchMode is actually not available until api 23. 
See:
https://developer.android.com/reference/android/hardware/camera2/CameraManager.html#setTorchMode(java.lang.String, boolean)

**Comment by nisrulz** [comment]
@bendavisnc You are right and its something which is very weird. I made a quick change and pushed the code to `develop` ,  you can check the commit [8cc1247fb66951e2fd263e72ce18e06bff78428d].

@ameerhamza6733 @0ximDigital @bendavisnc :
I donot have a device running android 5.1, so it would be really nice if someone can pull down my code and run the sample app with the updated code. Once tested I can push it out as a release.
Emulator testing isn't much use here because they donot support flashlight and are unreliable in this case.

Thank you for reporting the issue and also catching that specific anomaly

**Comment by bendavisnc** [comment]
I installed your app from the develop branch on my motorola g (api 22).
The light turns on just fine. 
The only thing I noticed was that I get a runtime exception when rotating my device ("RuntimeException: Fail to conect to camera service"). But I guess this is just something lacking with the actual sample app and not something missing with the library.

**Comment by soshial** [comment]
Tried master branch v1.1.2 on Huawei Honor 7, Android 5.0.2. Everything works pretty well, thanks!
