### ISSUE TITLE
Modify System settings

### ISSUE THREAD

**Issue by md0092651** [nisrulz/lantern#7]
When initializing the latern object using the below code 

 lantern = new Lantern(this)
                .checkAndRequestSystemPermission()
                .observeLifecycle(this);

its takes me to the settings page when it says "Can modify system settings". I dont know why we need this and how can this be avoided ?

**Comment by nisrulz** [comment]
Because when you add `.checkAndRequestSystemPermission()`  then it basically sends an intent message to open the system settings.

```
public Lantern checkAndRequestSystemPermission() {
        displayLightController.requestSystemWritePermission();
        return this;
    }
```
Check the source code for `requestSystemWritePermission()` here: https://github.com/nisrulz/lantern/blob/master/lantern/src/main/java/github/nisrulz/lantern/DisplayLightControllerImpl.java#L104

If you are not going to be using the Display as a flashlight i.e., the screen going full bright, then you can remove it from the init call.  Without this method being called this is how your init code will look like:

```
lantern = new Lantern(this)
.observeLifecycle(this);
```
> If `checkAndRequestSystemPermission()` is not called then the library cannot write to settings and thus any calls to display related methods will have no effect.

**Comment by nisrulz** [comment]
Assuming the question was answered, closing this issue.
